# profiles.yml - PUT THIS IN YOUR PROJECT FOLDER
final_prj_team:
  target: dev
  
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: final-prj-480309
      dataset: dbt_dev
      location: US
      threads: 4