# models/staging/schema.yml
version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - not_null
          
  - name: stg_employees
    columns:
      - name: employee_id
        tests:
          - unique
          - not_null