# models/staging/sources.yml
version: 2

sources:
  - name: raw_data
    database: final-prj-480309
    schema: dbt_dev  # Your raw tables are HERE!
    
    tables:
      - name: customer
      - name: employees
      - name: employee_privileges
      - name: orders
      - name: order_details
      - name: order_details_status
      - name: invoices
      - name: products
      - name: shippers
      - name: suppliers
      - name: strings
      - name: sales_reports
      - name: purchase_orders
      - name: purchase_order_details
      - name: inventory_transactions
      - name: inventory_transaction_types